"""Series 17 baker facts extracted from official bios + Wikipedia.

Bios themselves are copyrighted. This file stores structured facts we
extracted (age, job, signals), plus source URLs, not copied prose.
"""

from __future__ import annotations

S17 = {
    "series": 17,
    "year": 2026,
    "n_episodes": 10,
    "n_bakers": 12,
    "network": "Channel 4",
    "hosts": "Noel Fielding, Alison Hammond",
    "judge_1": "Paul Hollywood",
    "judge_2": "Nigella Lawson",
    "premiere": "2026-09-22",
    "uk_slot": "20:00 BST",
    "us_premiere": "2026-09-25",
    "us_platform": "Netflix Collection 14",
    "filming_location": "Welford Park",
}

# baker_short is the tent name. Surnames only when Wikipedia or the baker
# uses them publicly. Bracketology/OLBG extra surnames are flagged.
BAKERS = [
    {
        "baker_id": "17-clara",
        "baker_short": "Clara",
        "baker_full": "Clara Satchell-Silva",
        "age": 24,
        "occupation": "Marketing graduate",
        "hometown": "Hertfordshire, England (from Aveiro, Portugal)",
        "pronouns": "she/her",
        "years_baking_est": 2,
        "started_late": 1,
        "precision_job": 0,
        "chaos_self_describe": 1,
        "heritage_flavours": 1,
        "visual_showstopper": 1,
        "backup_baker": 0,
        "savoury_bias": 0,
        "notes": "Short stated tenure (cakes ~2 years). Visual/Portuguese flavour lane. Nigella-pleasure possible; Paul polish is the risk.",
        "bio_url": "https://thegreatbritishbakeoff.co.uk/meet-the-class-of-2026/",
        "name_source": "official+wikipedia",
    },
    {
        "baker_id": "17-connie",
        "baker_short": "Connie",
        "baker_full": "Connie",
        "age": 63,
        "occupation": "NHS hospital discharge lead",
        "hometown": "London, England",
        "pronouns": "she/her",
        "years_baking_est": 20,
        "started_late": 0,
        "precision_job": 0,
        "chaos_self_describe": 0,
        "heritage_flavours": 0,
        "visual_showstopper": 0,
        "backup_baker": 0,
        "savoury_bias": 0,
        "notes": "Known as the Cake Lady. Rum-soaked fruit. Cake-week specialist profile; bread/pastry/patisserie is the open question. Official materials use Connie only — no surname stored.",
        "bio_url": "https://thegreatbritishbakeoff.co.uk/meet-the-class-of-2026/",
        "name_source": "official",
    },
    {
        "baker_id": "17-danni",
        "baker_short": "Danni",
        "baker_full": "Danni",
        "age": 25,
        "occupation": "HGV service centre administrator",
        "hometown": "Dorset, England",
        "pronouns": "they/them",
        "years_baking_est": None,
        "started_late": 0,
        "precision_job": 0,
        "chaos_self_describe": 1,
        "heritage_flavours": 1,
        "visual_showstopper": 1,
        "backup_baker": 0,
        "savoury_bias": 0,
        "notes": "Official style line is chaos. Foraged + ube/red bean. High variance. Technical ranking may bite.",
        "bio_url": "https://thegreatbritishbakeoff.co.uk/meet-the-class-of-2026/",
        "name_source": "official",
    },
    {
        "baker_id": "17-gabe",
        "baker_short": "Gabe",
        "baker_full": "Gabe Capes",
        "age": 32,
        "occupation": "Artist and drag king",
        "hometown": "West Midlands, England (raised Grimsby)",
        "pronouns": "they/them",
        "years_baking_est": 19,
        "started_late": 0,
        "precision_job": 0,
        "chaos_self_describe": 0,
        "heritage_flavours": 0,
        "visual_showstopper": 1,
        "backup_baker": 0,
        "savoury_bias": 1,
        "notes": "Watched series 1 at 13. Homemade/gorgeous, savoury, meringue. Costume/visual skill. Pink News also lists he/they; default here is they/them.",
        "bio_url": "https://thegreatbritishbakeoff.co.uk/meet-the-class-of-2026/",
        "name_source": "official+wikipedia",
    },
    {
        "baker_id": "17-gary",
        "baker_short": "Gary",
        "baker_full": "Gary Harding",
        "age": 67,
        "occupation": "Retired garment technologist",
        "hometown": "Nottinghamshire, England",
        "pronouns": "he/him",
        "years_baking_est": 5,
        "started_late": 1,
        "precision_job": 1,
        "chaos_self_describe": 0,
        "heritage_flavours": 0,
        "visual_showstopper": 1,
        "backup_baker": 0,
        "savoury_bias": 0,
        "notes": "Oldest in the tent. Presentation analog from garment tech. Late starter. Winner mass at 67 is historically tiny (Nancy 60 is the outlier).",
        "bio_url": "https://thegreatbritishbakeoff.co.uk/meet-the-class-of-2026/",
        "name_source": "official+wikipedia",
    },
    {
        "baker_id": "17-mo",
        "baker_short": "Mo",
        "baker_full": "Mo",
        "age": 21,
        "occupation": "Law student",
        "hometown": "West Midlands, England",
        "pronouns": "he/him",
        "years_baking_est": 12,
        "started_late": 0,
        "precision_job": 0,
        "chaos_self_describe": 1,
        "heritage_flavours": 1,
        "visual_showstopper": 0,
        "backup_baker": 0,
        "savoury_bias": 0,
        "notes": "Youngest. Self-describes chaotic/random but now 'precise, professional-looking'. Asian-British flavours. Official age is 21 (ignore Good Housekeeping 32). Official materials use Mo only — no surname stored.",
        "bio_url": "https://thegreatbritishbakeoff.co.uk/meet-the-class-of-2026/",
        "name_source": "official",
    },
    {
        "baker_id": "17-molly",
        "baker_short": "Molly",
        "baker_full": "Molly Chauhan",
        "age": 31,
        "occupation": "Accessibility coordinator",
        "hometown": "London, England",
        "pronouns": "she/her",
        "years_baking_est": 25,
        "started_late": 0,
        "precision_job": 0,
        "chaos_self_describe": 0,
        "heritage_flavours": 0,
        "visual_showstopper": 0,
        "backup_baker": 0,
        "savoury_bias": 0,
        "notes": "Baking 25+ years from grandmother. Traditional flavours. Cross-stitch patience/detail. Consistency profile.",
        "bio_url": "https://thegreatbritishbakeoff.co.uk/meet-the-class-of-2026/",
        "name_source": "official+wikipedia",
    },
    {
        "baker_id": "17-moyin",
        "baker_short": "Moyin",
        "baker_full": "Moyin Odeniran",
        "age": 22,
        "occupation": "Political economy student",
        "hometown": "Essex, England",
        "pronouns": "he/him",
        "years_baking_est": 17,
        "started_late": 0,
        "precision_job": 1,
        "chaos_self_describe": 0,
        "heritage_flavours": 1,
        "visual_showstopper": 0,
        "backup_baker": 0,
        "savoury_bias": 0,
        "notes": "Macaronage by 14 is the strongest on-paper technical signal in this class. Nigerian flavours. County 100m champion — discipline analog.",
        "bio_url": "https://thegreatbritishbakeoff.co.uk/meet-the-class-of-2026/",
        "name_source": "official+wikipedia",
    },
    {
        "baker_id": "17-nikki",
        "baker_short": "Nikki",
        "baker_full": "Nikki",
        "age": 50,
        "occupation": "Advertising post-producer",
        "hometown": "London, England",
        "pronouns": "she/her",
        "years_baking_est": 43,
        "started_late": 0,
        "precision_job": 0,
        "chaos_self_describe": 0,
        "heritage_flavours": 0,
        "visual_showstopper": 1,
        "backup_baker": 0,
        "savoury_bias": 0,
        "notes": "Visual-industry job. Baking from age 7. Middle of the age curve's right tail. Not an obvious technical prodigy from the bio.",
        "bio_url": "https://thegreatbritishbakeoff.co.uk/meet-the-class-of-2026/",
        "name_source": "official",
    },
    {
        "baker_id": "17-shannon",
        "baker_short": "Shannon",
        "baker_full": "Shannon",
        "age": 29,
        "occupation": "Project planner and scheduler",
        "hometown": "Gloucestershire, England (grew up Bristol)",
        "pronouns": "she/her",
        "years_baking_est": 20,
        "started_late": 0,
        "precision_job": 1,
        "chaos_self_describe": 0,
        "heritage_flavours": 0,
        "visual_showstopper": 0,
        "backup_baker": 1,
        "savoury_bias": 0,
        "notes": "Timings job is the on-the-nose Bake Off analog. Rustic/whimsical vs Paul polish is the risk. Confirmed 2025 reserve baker in a Media Mole Q&A — tent experience, not a winner lock. Official materials use Shannon only.",
        "bio_url": "https://thegreatbritishbakeoff.co.uk/meet-the-class-of-2026/",
        "name_source": "official",
        "backup_source": "https://mediamole.co.uk/tv/the-great-british-bake-off-2026-shannon-age-job-qa/33820/",
    },
    {
        "baker_id": "17-tom",
        "baker_short": "Tom",
        "baker_full": "Tom Whittaker",
        "age": 25,
        "occupation": "Hairdresser",
        "hometown": "West Yorkshire, England",
        "pronouns": "he/him",
        "years_baking_est": 19,
        "started_late": 0,
        "precision_job": 0,
        "chaos_self_describe": 0,
        "heritage_flavours": 0,
        "visual_showstopper": 1,
        "backup_baker": 0,
        "savoury_bias": 0,
        "notes": "Brandy snaps before 10. Hairdressing = hands/presentation. Strong TV-character bio. Sugarwork childhood ≠ bread/pastry.",
        "bio_url": "https://thegreatbritishbakeoff.co.uk/meet-the-class-of-2026/",
        "name_source": "official+wikipedia",
    },
    {
        "baker_id": "17-yannis",
        "baker_short": "Yannis",
        "baker_full": "Yannis",
        "age": 28,
        "occupation": "Paediatric doctor",
        "hometown": "London, England (born Vienna)",
        "pronouns": "he/him",
        "years_baking_est": None,
        "started_late": 0,
        "precision_job": 1,
        "chaos_self_describe": 0,
        "heritage_flavours": 1,
        "visual_showstopper": 0,
        "backup_baker": 0,
        "savoury_bias": 0,
        "notes": "NICU doctor, pastry self-ID, Bangladeshi/Austrian flavour range. Bake Off helped him learn English. Medical analog: Jasmine (S16) was a medical student. Not predictive, but the pool will notice.",
        "bio_url": "https://thegreatbritishbakeoff.co.uk/meet-the-class-of-2026/",
        "name_source": "official",
    },
]
